### ISSUE TITLE
Is there test data for graph generation?

### ISSUE THREAD

**Issue by tomjaguarpaw** [awf/ADBench#106]
Is there any test data for graph generation?  At the moment I can't test the graph generation with violation info because I would have to generate the correctness files by hand.  If there is no test data then perhaps we can put some in a suitable directory.

**Comment by msdmkats** [comment]
No there's not.

To think of it, I'd rather not have any in the repository, because if we put it there, it will inevitably go stale - data formats are subject to change.

So, I suggest generating some new data using the actual version of the code every time.
To generate data with violations, just make tolerance for `Finite` inadequately low, e.g. `1e-12`.

**Comment by tomjaguarpaw** [comment]
Seems like a reasonable solution.
