### ISSUE TITLE
Ensure that our Powershell code runs on Linux

### ISSUE THREAD

**Issue by tomjaguarpaw** [awf/ADBench#26]
Check whether it does now.  If it doesn't then tweak the code so that it does.

**Comment by athas** [comment]
I'm still trying to get it working, but I did find one problem and a fix.  The `run-all.ps1` script uses `mkdir -force $dir_out` a number of places, because Powershell will try to run `/bin/mkdir`, which does not have that option.  I think it corresponds to `mkdir -p` on Linux, but presumably that will not work on Windows.  Googling suggests that the following will work:

```
New-Item $dir_out -ItemType Directory -ea 0
```

Certainly works on my Linux; haven't tested on Windows.

**Comment by athas** [comment]
I found some more issues:

* Use of backslashes in paths (just make these forward slashes; Windows isn't picky).
* Assumption of an `.exe` extension on at least some binaries (Windows doesn't require this in the console, but I'm not sure about Powershell).
* The script assumes that the `cmake`-built binaries are in a directory corresponding to the build type (Release/Debug).  I think Visual Studio will generate these by default, but `make` will not, and instead place make the binaries at e.g. `my-build/tools/Finite/Tools-Finite-GMM`.  I'm quite a `cmake` novice, so I'm not sure how to force `cmake` to create these directories on Linux.

**Comment by athas** [comment]
I've been running the run-all.ps1 script a lot recently.  There may still be various small bugs left, but I think this issue can be closed.

**Comment by tomjaguarpaw** [comment]
Good to know.  Thanks for confirmation!
