### ISSUE TITLE
Tapenade produces wrong output

### ISSUE THREAD

**Issue by msdmkats** [awf/ADBench#91]
Subject. When I run `run-all.ps1` with tapenade module enabled, jacobians saved in `..._J_Tapenade.txt` files for all GMM, BA, and LSTM problems are entirely wrong. Jacobians for hand are fine, btw. Interestingly, unit test for LSTM jacobian computation passes, but the jacobian that end up being saved for the very same problem is, as I said, completely wrong.

**Comment by mikhailnikolaev** [comment]
The problem is found.

First of all, in the reverse mode Tapenade generates a code which calculates the next operation:
```
dx = J* dy
```
Here __J*__ is a transpose jacobian of the original function. So, you give this code some element of __dy__ space Carthesian basis and get respective column of a __J*__ (i.e. row of __J__). But after each running generated code sets its input (i.e. __dy__, not other parameters) to zero. Thus, if you run this code in a cycle and do not reinitialize __dy__, you will get a correct answer only at the first time. After that you will get only zeros.

Secondly, Tapenade produce wrong code that has to be repaired. But I figured out that some mistakes are still in the code, but weren't found because they fluence on the code in a multiple running scenario. Such mistakes are the same as in the given code part:
```C++
*alphasb = 0.0;
...
for (ik = k-1; ik > -1; --ik) {
            ...
            alphasb[ik] = alphasb[ik] + main_termb[ik];
...
```
This line is from the file *gmm_b_tapenade_generated.c* (396-404). As you can see Tapenade generated code must intialize _alphasb_ variable (which further will store a part of jacobain) with zeros, but do it wrong. So, even if external code that calls this function set _alphasb_ with zeros in the first time, the second time this variable will hold part of jacobian and this code calculates wrong values. So, this also leads to a problem in scenario when jacobian calculated multiple times.
